DeterminateSystems/fh

Cargo.lock
Cargo.toml
src/cli/cmd/list.rs
src/cli/cmd/mod.rs
src/cli/cmd/search.rs
src/cli/mod.rs

Examples:
```shell
fh list versions nixos/nixpkgs "0.2305.*"
fh list versions DeterminateSystems/nuenv "*"
fh list versions eza-community/eza "0.10"
```
Note that this requires a backend change (currently in review).

List flake versions matching a constraint

---

src/cli/cmd/list.rs
src/cli/cmd/mod.rs

I'm marking this as a draft because it depends on backend changes, namely returning project/org for the flake instead of name/org. I could've used Serde aliasing for that but I'd prefer to streamline the backend instead.

Enable listing flakes by label

---

flake.lock
flake.nix

Just a minor nit. Better to not give people the wrong idea about FlakeHub URLs in a repo like this.

Remove api. from FlakeHub URLs and run flake update

---

src/cli/cmd/add/flake.rs
src/cli/cmd/convert.rs

Extends convert to support more cases.
URI-types become strings:
```diff
fenix = {
-      url = github:nix-community/fenix;
+      url = "https://flakehub.com/f/nix-community/fenix/0.1.1618.tar.gz";
inputs.nixpkgs.follows = "nixpkgs";
};
```
and IndentedStrings, such as they are, are converted too:
```diff
-     flake-utils.url = ''github:numtide/flake-utils'';
+     flake-utils.url = ''https://flakehub.com/f/numtide/flake-utils/0.1.87.tar.gz'';
```
and nixpkgs/release-mm.yy are supported -- migrated to releases now.
Also, while running fh across every determinatesystems project, I found another issue. When a flake.nix looks like this:
```nix
{
inputs.nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
inputs.rust-overlay.url = "github:oxalica/rust-overlay"; …
```

Additional inputs

---

src/cli/cmd/init/handlers/rust.rs
src/cli/cmd/init/handlers/tools.rs

Provides support for a bunch of fun stuff

Support more tools for `fh init`

---

assets/default.nix
assets/flake.hbs
assets/shell.nix
src/cli/cmd/init/handlers/mod.rs
src/cli/cmd/init/handlers/php.rs
src/cli/cmd/init/handlers/rust.rs
src/cli/cmd/init/mod.rs
src/cli/cmd/init/template.rs

This PR adds support for `flake-compat` to the `fh init` command. If you say yes to the prompt, you get a `default.nix`, a `shell.nix`, and a `flake-compat` input in your `flake.nix`.
I've tested that this works using these steps:
```shell
fh init
nix-shell
[nix-shell:~/example-flake]$ which curl
/nix/store/kmiapnigv92jwhpzqk2w9mjk0y8y8s6b-curl-8.1.1-bin/bin/curl
```

Add support for `flake-compat` to `fh init`

---

src/cli/cmd/add/mod.rs

Treats ryantm/agenix/ the same as ryantm/agenix.
---
Fixes https://github.com/DeterminateSystems/fh/issues/66.

Trim trailing /s from flakerefs

---

samples/flake8.test.nix
src/cli/cmd/convert.rs
src/cli/cmd/eject/mod.rs
src/cli/cmd/mod.rs
src/main.rs

This does a best-effort attempt at migrating a user from using FlakeHub inputs back to GitHub inputs. The process is unfortunately lossy, so it may not always produce the correct "previous state". In these cases, it may be less effort to revert the initial changes that `fh convert` made.

fh eject: init

---

src/cli/cmd/init/handlers/mod.rs
src/cli/cmd/init/handlers/php.rs
src/cli/cmd/init/handlers/python.rs
src/cli/cmd/init/handlers/ruby.rs

With this change ruby_version_attr will be ruby_3_2 and not ruby_32 which is not a valid package.
Fixes https://github.com/DeterminateSystems/fh/issues/77

version_as_attr_default

---

src/cli/cmd/init/handlers/javascript.rs

This improves our detection of Bun, as I suspect `bun.lockb` files are more widely used than `bunfig.toml` (though I could be wrong).

Detect bun.lockb file

---

flake.nix

Closes https://github.com/DeterminateSystems/fh/issues/86.

flake: on darwin, disable tests that rely on local networking

---

Cargo.lock
Cargo.toml
src/cli/cmd/add/mod.rs
src/cli/cmd/eject/mod.rs
src/cli/cmd/init/mod.rs

There's nothing really "new" in this release per se, but we're bumping this on the pragmatic grounds that it will un-break people trying to run it from `*.tar.gz`.

Bump version to 0.1.9

---

src/cli/cmd/init/handlers/python.rs

Adds pyproject.toml to the list of files that are checked before showing the Python prompts.

Add pyproject.toml detection

---

Cargo.lock
Cargo.toml
src/cli/cmd/login/mod.rs
src/cli/mod.rs

* Shunt the user through the frontend instead of the api backend for token creation
* Give the token a default description
* Offer suggestions on what to add to the nix.conf and restarting the daemon

Set up binary cache bits

---

.github/workflows/build.yml

An oversight on our part. This bring `fh` in line with `flake-checker` and other projects.

Add ARM builds to CI

---

.github/workflows/release-prs.yml

Directly mimics https://github.com/DeterminateSystems/flake-checker/pull/118

Stop unnecessary per-PR builds

---

Cargo.lock
Cargo.toml
flake.lock
flake.nix

Using the `rustls-tls` feature for `reqwest` is nice because it avoids a dependency on OpenSSL, but it comes at the cost of ignoring system certs in favor of bundled certs, which creates problems on systems that require custom certs. The `rustls-tls-native-roots` feature enables us to avoid the OpenSSL dependency while also using system certs.
This PR also has the pleasant side effect that we no longer need to disable tests for macOS.

Switch reqwest to rustls-tls-native-roots

---

src/cli/cmd/add/mod.rs
src/cli/cmd/eject/mod.rs
src/cli/cmd/init/mod.rs
src/cli/cmd/list.rs
src/cli/cmd/login/mod.rs
src/cli/cmd/mod.rs
src/cli/cmd/search.rs
src/cli/cmd/status/mod.rs

This PR changes up the HTTP client for FlakeHub to optionally use authentication for some endpoints.
> [!NOTE]
> This PR also fixes `fh list orgs`, which, I just now found out, is currently broken.

Add authentication to core FlakeHub client

---

src/cli/cmd/init/mod.rs

This is, of course, not currently a valid flake reference

Fix FlakeHub URL for flake-compat

---

Cargo.lock
Cargo.toml
flake.lock
flake.nix
shell.nix
src/cli/cmd/convert.rs
src/cli/cmd/eject/mod.rs
src/cli/cmd/login/mod.rs
src/cli/cmd/mod.rs
src/cli/instrumentation.rs
src/main.rs
src/shared/mod.rs

* Adds some dependencies for tokio/axum/http, bumps axum-test and fixes some test cases.
* Adds initial support for login via UDS and DNEE - this is done with axum + http1 transport. I'm not sure that was the *best* choice, but it was *a* choice, and I suppose we can change it in the future if we want. But I wanted to go with something I was at least marginally familiar with.
Leaving as a draft, there's a couple comments to remove, some more testing to do, and some changes needed to the corresponding DNEE PR.

login: support login via determinate-nix-ee via UDS socket

---

src/cli/cmd/login/mod.rs

Apparently "substituters" is hard for me to spell.
This should merge after #128.

login: nix.conf s/extra-trusted-substituters/extra-substituters/g

---

src/cli/cmd/login/mod.rs
src/cli/cmd/mod.rs
src/cli/cmd/status/mod.rs
src/shared/mod.rs

This is mostly to accommodate the change made to `determinate-nixd`: https://github.com/DeterminateSystems/determinate-nixd/pull/59 . To share the `merge_nix_configs` function.
There's another minor change that renames the `auth_token_path` function to reflect that it's the user auth token path.

uds2: move merge_nix_configs to shared

---

src/cli/cmd/login/mod.rs
src/main.rs
src/shared/mod.rs

Closes #144 
Commit one moves all the "no-dnixd" code into the branch where we don't use it.
Commit two stops writing to the dnixd state directory when dnixd isn't available.

Do less without dnixd

---

src/cli/cmd/apply/mod.rs

This resolves a problem when a user may attempt to write to /result on macOS in certain circumstances.

Don't create a result symlink when using fh apply

---

flake.lock
src/cli/cmd/apply/mod.rs
src/cli/cmd/mod.rs
src/cli/error.rs

Right now, the error output for path resolution is pretty confusing:
```
Error: 
0: http error: error decoding response body: invalid type: string "Flake `foo/bar` not found.", expected struct ResolvedPath at line 1 column 47
1: error decoding response body: invalid type: string "Flake `foo/bar` not found.", expected struct ResolvedPath at line 1 column 47
2: invalid type: string "Flake `foo/bar` not found.", expected struct ResolvedPath at line 1 column 47
```
This PR makes that error output more granular.

Improve error output for path resolution

---

Cargo.lock
Cargo.toml
src/cli/cmd/init/mod.rs
src/cli/cmd/mod.rs

This PR changes the behavior of the `command_exists` function to return a Boolean rather than a `Result`. This enables us to handle missing commands a bit more gently.

Change fh init behavior when executables aren't installed

---

flake.lock
src/cli/cmd/init/handlers/go.rs
src/cli/instrumentation.rs

The current logic misnames Go versions as e.g. 20 instead of 1.20. This fixes that. It also brings the suggested Go version in line with what's currently available in 24.11.

Fix Go version logic in handler

---

flake.lock
src/cli/cmd/apply/mod.rs
src/cli/cmd/fetch.rs
src/cli/cmd/mod.rs
src/main.rs
src/shared/mod.rs

This PR is an initial implementation of `fh fetch`. Users can request an out link with `--out-link`. This is supported natively in nix 2.26, so on lower versions we manually create a symbolic link.

Initial implementation of `fh fetch`

---

.github/workflows/update-flake-lock.yaml
flake.lock
flake.nix

We occasionally have PR runs stymied by out-of-date Nixpkgs violations, so better to be proactive about it.

Update flake.lock and add update-flake-lock support

---

.github/workflows/flakehub-cache.yml

Part of a general effort to ensure that we use our own tools properly in our own repos.

Remove use-flakehub param in CI

---

src/cli/cmd/login/mod.rs
src/dnixd.rs
src/main.rs

fh login  was created before Determinate Nix and determinate-nixd existed. In fact, fh login being _so hard_ to get right is a big reason determinate-nixd came to be. Now, fh login is intended for folks who are not on Determinate Nix. ...and I'd sort of prefer they used Determinate Nix, anyway, because of how hard it is to get right.

Tell Determinate Nix users to use determinate-nixd login instead of fh login

---

flake.nix

Makes it possible to build FlakeHub via `pkgsCross.riscv64.fh`, I have not tested 32-bit support but this should work.

Make FlakeHub buildable for RISC-V
